title: "Heesung Yun"
description: "Cybersecurity Portfolio"
url: "https://heesungyun.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:title/
