#title: "Heesung Yun"
#description: "Cybersecurity Portfolio"
#url: "https://heesungyun.github.io"
#baseurl: ""
#remote_theme: "mmistakes/minimal-mistakes"

#plugins:
#  - jekyll-include-cache

# Optional but recommended
#markdown: kramdown
#kramdown:
#  input: GFM

#
# 다음 설정은 사이트가 올바르게 빌드되기 위해 필수적입니다.
#

# 사이트의 URL, 끝에 슬래시(/)를 포함하지 마십시오.
url: "https://heesungyun.github.io" 

# 사이트의 기본 URL. 사용자 레벨 사이트의 경우 빈 문자열이어야 합니다.
baseurl: ""

# 사용할 원격 테마. al-folio의 GitHub 리포지토리에서 테마를 가져옵니다.
remote_theme: alshedivat/al-folio
# 참고: al-folio의 리포지토리 이름이 다른 경우 여기를 업데이트하십시오.

# GitHub Pages는 jekyll-remote-theme 플러그인을 명시적으로 활성화해야 합니다.
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  # 여기에 al-folio가 사용하는 다른 플러그인을 추가하십시오.

#
# 다음은 권장되는 개인화 설정입니다.
#
title: Heeseung Yun
description: "Ph.D. student at Seoul National University Vision and Learning Lab."
author:
  name: "Heeseung Yun"
  email: "heeseung.yun@vision.snu.ac.kr"
  # avatar: /assets/img/your-photo.jpg # 아바타 이미지 예시 경로

# 소셜 미디어 링크 (정확한 키는 al-folio 문서를 확인하세요)
social:
  github: heesungyun # 또는 사용자의 리포지토리에 따라 heesung6701
  # twitter: your_twitter_handle
  # scholar: your_google_scholar_id
