title: "Heesung Yun"
description: "Cybersecurity Portfolio"
url: "https://heesungyun.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

# Optional but recommended
markdown: kramdown
kramdown:
  input: GFM
